trigger:
- produccion

pool:
  name: Default

steps:
- script: node --version
  displayName: 'Verificar Node.js'

- script: npm install
  displayName: 'Instalar dependencias'

- script: npm test
  displayName: 'Correr tests'