trigger:
- produccion

pool:
  name: Default

steps:
- script: |
    "C:\nvm4w\nodejs\node.exe" --version
  displayName: 'Verificar Node.js'

- script: |
    "C:\nvm4w\nodejs\npm.cmd" install
  displayName: 'Instalar dependencias'

- script: |
    "C:\nvm4w\nodejs\npm.cmd" test
  displayName: 'Correr tests'